name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build webR
    runs-on: ubuntu-latest
    container: ghcr.io/r-wasm/flang-wasm:main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install required system packages
        run: apt-get update && apt-get install -y gh jq sudo
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Install required R packages for building documentation
        run: Rscript -e 'install.packages(c("rmarkdown", "rvest"))'
      - name: Configure webR for flang
        env:
          EMFC: /opt/flang/host/bin/flang-new
        run: ./configure
      - name: Setup Emscripten PATH
        run: echo "/opt/emsdk:/opt/emsdk/upstream/emscripten" >> $GITHUB_PATH
      - name: Set Emscripten EM_NODE_JS
        run: echo "EM_NODE_JS=$(which node)" >> $GITHUB_ENV
      - name: Build all optional wasm libs
        env:
          EMSDK: /opt/emsdk
        run: cd libs && make all
      - name: Build webR
        env:
          EMSDK: /opt/emsdk
        run: make && make check-pr
      - name: Build webR documentation
        run: cd src/docs && make

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Project for Deployment
        run: |
          # Add commands to build your project here
          # For example, if you're using a static site generator:
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/_site  # or the path to your build directory
